import typing
import os


def suffix_array(text: str) -> typing.List["int"]:
    """
    Return a list of indices in lexigraphical order of all suffixes in text, starting with $.
    """
    if text[-1] != "$":
        text = text + "$"
    suffixes = {text[-i:]: len(text) - i for i in range(1, len(text) + 1)}
    indices = []
    sorted_keys = sorted(list(suffixes.keys()))
    for key in sorted_keys:
        indices.append(suffixes.get(key))
    return indices


if __name__ == "__main__":
    text = "ATATAGGCACATAAGTGGCGGGGTTTGTGGACTGGGAGTTGTCTCCTCTTGGATTAGACCCGGGATCGTCGCTTAGTCGAATAGCGCTTTAAGACGATAAAGGGCTGCTCTGTTGGTCCTTCGGGGCCTTACAAGTTGCTTGACAACTGTAGTGAGCTGTCTCTATCAGCTGTCGACGGGCTGAAAATAGTCATAATAAAATCCCGCTAGATACCTACACGGGATCATATATGTACTTCAGAGTACATAAAAGTAACGACAACAGAACCGTAGAAGAGGGGGTGACAGCTTCTTTGTGTGCTTAGGAATTGTTCGGTCAAGTTTTCGTTGTGGACGTGGGAATCCTCGCCATGTGTCATGTTATTTCTTCTACTTAGATGAGTCTTGTTAATTGAAGGACTTGCCCTGTGGGAAGGTCAATGATTTCTTCCCGCAAGGCTTTTTTCCGCCCCCTGGAGATAAAAGGCCTCCCAAGGTCCATTTCTCGGTGATGTTTGTTGTGAGGTGCGCGTTCGCCTTAGGCGAGGTATTACTTTAGTTAGGGGTACTGGTCTCTGAGTCGCACGGGGCTGGGGGCGCACATCTAGAACGGGGAAGATTGATCCCCAACCACTACGGTGAATATTATAGGAACCGACCATTAGCGGGGATTGGTTCTATAGTTACCTGCTTCTCCGCCTGCTTGAACTTCAAATTTTGGGCTAGGGGTAAGGGGGTACCTAACGTTCGTTTACGAGAAAAATTCCTTCCGTCAATAACCATAGAAGCAGAAGAACAAGCCCACTTCACCTGATAATACCAATCGCCTGATTCCCAGACGGGAGGTTCTAATAACGGGGTGTTTTCTATTGGAACTACCGCATAATGGAAGCCTAAATACGCGGTCGTTAACGAGATAAGTGTAGTAAACTGATAAAATATGGCT$"
    script_dir = os.path.dirname(__file__)
    indices = suffix_array(text)
    with open(f"{script_dir}/output.txt", "w") as f:
        f.write(" ".join(str(i) for i in indices))
